version: "3.8"
services:
  api:
    container_name: llm
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    environment:
      PORT: 8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    restart: always